@baseUrl = http://localhost:8180
@contentType = application/json

POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
    "nom": "Test User",
    "email": "test@gmail.com",
    "motDePasse": "test",
    "entityId": 1,
    "roleId":11
}



POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email":"test@gmail.com",
    "motDePasse":"test"
}

